### ISSUE TITLE
The World's Most Boring Build System

### ISSUE THREAD

**Issue by jezen** [pwdo/FFC6-Call-For-Speakers#18]
# The World's Most Boring Build System
## About myself
- Name: Jezen Thomas
- Country of Origin: United Kingdom
- Occupation & Company: Software Developer at UXPin
- URL to my website: http://jezenthomas.com/
## About my topic

My talk is about front-end development workflow. Specifically, it is about removing the complexity of JavaScript build systems, and adopting a simpler, more stable, more battle-tested approach with old (yet immensely powerful!) Unix tools. Here's the abstract:

The front-end community has matured immensely in the past five years with automated build systems and package managers written in JavaScript becoming commonplace. But how did we get here? And what has this really cost us? We know every line of code is a liability, and the best line of code is the one that doesn't exist. JavaScript build systems are complicated and verbose, and it doesn't need to be this way.

If you're using hip new tools like Grunt, Gulp, and Bower, you could make your life so much easier by embracing tools that were around 40 years ago. Even if you've never ventured outside the world of JavaScript, come and learn how these general problems are elegantly solved with the Unix philosophy. We'll look at the simplest possible approach to automated front-end development, and you'll be able to strip away literally thousands of lines of code while developing a deeper understanding of the tools you rely on.

My talk is most suitable for developers, and designers who dabble in front-end development. The topic is interesting to developers of all skill levels, and no experience of Make, Bash, or anything on the command line is required.
## Additional info
- I've spoken before at SoCraTes 2014 in Soltau, Germany. I don't have any footage, unfortunately. I will be speaking at UXPin's office on September 24th, and at Falsy Values conference in Warsaw on October 12th.
- I'll need travel costs covered between Manila and Gdansk, Poland.

**Comment by juliankrispel** [comment]
I've seen this talk at Falsy Values and it's pretty awesome :+1: :+1: :+1: :+1:
