### ISSUE TITLE
The web of space - WebGL and WebVR

### ISSUE THREAD

**Issue by AVGP** [pwdo/FFC6-Call-For-Speakers#25]
# The web of space - WebGL and WebVR
## About myself
- Name: Martin Naumann
- Country of Origin: Switzerland
- Occupation & Company: Bit Wizard at Archilogic
- URL to my website: http://beta.archilogic.com
## About my topic

Let's talk about how we can use 3D on the web to better represent, explore and explain space and our environment...and then go beyond just that and take our users to other places by immersing them into virtual Reality. All from the comfort of your browser window!

This talk is for both designers, who wanna learn more about the possibilities of augmenting content with 3D and explore the new possibilities of virtual reality and developers who wanna see how they can build virtual spaces and worlds using Javascript.

There's a bit of code where Javascript knowledge is useful, but it's resulting in visuals, so people can easily skip the code and focus on going "WOW" when they see the output :-)
## Additional info
- I've spoken at a range of events on different topics, see http://geekonaut.de/speaking
- I'll need travel & accomodation from Zurich (ZRH), but I'm pretty flexible. Cheap flights & a couch are fine by me.

**Comment by juliankrispel** [comment]
:trollface:

**Comment by sophialucero** [comment]
Hi Martin, 

We have decided to go in a different direction regarding our roster of speakers this year. We will, however, keep you in mind for future events. Thank you for your submission!
