### ISSUE TITLE
User Experience needs a better experience. 

### ISSUE THREAD

**Issue by tyrale** [pwdo/FFC6-Call-For-Speakers#7]
# User Experience needs a better experience.
## About myself
- Name: _Tyrale Bloomfield_
- Country of Origin: _United States_
- Occupation & Company: _UX Lead_
- URL to my website: _https://joinspartan.com_
## About my topic

A new UX process that fits inside of Agile, can account for experiences outside of "pages", and provides tools for designing the internet of things. 

UX Triage will step through and educate on a 5 step process you can take to work tomorrow. 
1. Understand - a few activities to surface the needs, wants & desires of a feature or product. 
2. Experience Mapping - See|Do maps and how they are used. 
3. Atom Gathering - the missing workflow of Atomic Design.
4. Gray models - more than wireframes, much, much more. 
5. Interaction models - how it feels or behaves works over what is on the page.

This process can be developed for a product or feature in minutes and hours versus days or weeks. All while developers and clients are involved. 

We will cover what these steps include, and how you can start using a new UX process now.

UX Triage is a new process that has been tested in real world development, across multiple countries. 

Jared Spool, a founder of User Experience Design, saw this at the Chattanooga Startup Week and asked me to present to his students at the new UX school Centre Center. He mentioned that it is a great process, and he can see how it fits very well with modern development techniques.

Suitable for anyone involved in the design & development process, the goal is to better the communication and deliverables between the all involved on a project. Client, Designer & Developer. 
## Additional info
- Medium Article to support this topic. http://bit.ly/1GUVuV3 
- No videos of previous talks, but I have spoken at many Meetups on UX, UI, Development, & Startups. My style is upbeat, fresh, with some humor. 
- I'd like to request travel expenses and accommodations covered for the conference.

**Comment by tyrale** [comment]
no permission to add a label :(

**Comment by chakler** [comment]
@tyrale Oops! We didn't notice there's now way for non-contributor/owner to add label. Thanks for letting us know. We'll change the instruction asap. :smiley:

**Comment by tyrale** [comment]
After speaking at a few more conferences and getting feedback from industry founders in UX, like Jared Spool, I have refined my proposal. Thanks for reviewing.
